// Alt-URL-Weiterleitungen (Webflow-Erbe) als Pages-Middleware.
// GRUND (04.09.2026): Cloudflare Pages wertet in _redirects nur die ersten 100 statischen Regeln aus, alles danach
// fiel still weg (198 URLs aus der Google Search Console waren 404, u.a. /winterthur-de mit 2600 Klicks/Jahr).
// Hier gibt es kein Limit. _redirects enthaelt nur noch die Marketing-Kurzlinks (Probetraining/Trial).
// Pruefung: alle URLs aus dem GSC-Export (Pages.csv) per curl -L muessen auf 200 enden (Skript siehe CLAUDE.md).
// Reihenfolge: exakter Treffer (ohne Endslash, case-insensitiv) -> Slug-Regeln (Ziel wird per ASSETS geprueft) -> Prefix-Regeln.
// /assets/* ist via _routes.json von der Middleware ausgenommen (spart Function-Aufrufe).
const EXACT = {
  "/401": ["/", 302],
  "/about": ["/en/about/", 301],
  "/access-denied": ["/", 302],
  "/agb-kidstraining": ["/agb-kindertraining/", 301],
  "/bjj-winterthur.html": ["/winterthur/kurse/bjj/", 301],
  "/blog": ["/articles/", 301],
  "/blog/are-martial-arts-for-me": ["/articles/are-martial-arts-for-me/", 301],
  "/blog/female-success-stories-the-first-step-is-always-the-hardest": ["/articles/female-success-stories-the-first-step-is-always-the-hardest/", 301],
  "/blog/july-highlights---the-journey-was-worth-every-step": ["/articles/july-highlights---the-journey-was-worth-every-step/", 301],
  "/blog/socializing-after-the-mats": ["/articles/socializing-after-the-mats/", 301],
  "/blog/winterthur-combat-sports-boom-mma-and-muay-thai-at-impact-martial-arts": ["/articles/winterthur-combat-sports-boom-mma-and-muay-thai-at-impact-martial-arts/", 301],
  "/blog/zero-ego-100-heart-impact-community-open-mat-recap": ["/articles/zero-ego-100-heart-impact-community-open-mat-recap/", 301],
  "/cancellation": ["/en/cancellation/", 301],
  "/career": ["/karriere/", 301],
  "/career/bjj-coach": ["/karriere/bjj-coach/", 301],
  "/career/head-coach": ["/karriere/head-coach/", 301],
  "/career/martial-arts-coach": ["/karriere/", 301],
  "/career/mma-coach": ["/karriere/mma-coach/", 301],
  "/career/muay-thai-boxing-coach": ["/karriere/muay-thai-boxing-coach/", 301],
  "/career/sales": ["/karriere/sales/", 301],
  "/checkout": ["/", 302],
  "/class/bjj": ["/en/zurich/classes/bjj/", 301],
  "/class/boxing": ["/en/zurich/classes/boxing/", 301],
  "/class/fitness-kickboxing": ["/en/zurich/classes/fitness-kickboxing/", 301],
  "/class/kickboxing": ["/en/zurich/classes/fitness-kickboxing/", 301],
  "/class/little-ninjas": ["/en/zurich/classes/little-ninjas/", 301],
  "/class/mma": ["/en/zurich/classes/mma/", 301],
  "/class/mma-street-defense": ["/en/zurich/classes/street-defense/", 301],
  "/class/personal-training": ["/en/zurich/classes/personal-training/", 301],
  "/class/self-defense-for-women": ["/en/zurich/classes/street-defense/", 301],
  "/class/thai-boxing-muay-thai": ["/en/zurich/classes/muay-thai/", 301],
  "/class/winterthur-bjj": ["/en/winterthur/classes/bjj/", 301],
  "/class/winterthur-boxing": ["/en/winterthur/classes/boxing/", 301],
  "/class/winterthur-fitness-kickboxing": ["/en/winterthur/classes/fitness-kickboxing/", 301],
  "/class/winterthur-little-ninjas": ["/en/winterthur/classes/little-ninjas/", 301],
  "/class/winterthur-mma": ["/en/winterthur/classes/mma/", 301],
  "/class/winterthur-mma-street-defense": ["/en/winterthur/classes/street-defense/", 301],
  "/class/winterthur-personal-training": ["/en/winterthur/classes/personal-training/", 301],
  "/class/winterthur-self-defense-for-women": ["/en/winterthur/classes/street-defense/", 301],
  "/class/winterthur-thai-boxing-muay-thai": ["/en/winterthur/classes/muay-thai/", 301],
  "/class/winterthur-wrestling": ["/en/winterthur/classes/wrestling/", 301],
  "/class/wrestling": ["/en/zurich/classes/wrestling/", 301],
  "/coach/joao-wt": ["/en/winterthur/team/", 301],
  "/coach/laszlo-simo-wt": ["/en/winterthur/team/", 301],
  "/coach/ruben-crawford-wt": ["/en/winterthur/team/", 301],
  "/coach/sam-wt": ["/en/winterthur/team/", 301],
  "/coach/samuel-s-bauer-wt": ["/en/winterthur/team/", 301],
  "/coach/sergei-wt": ["/en/winterthur/team/", 301],
  "/coaches": ["/en/zurich/team/", 301],
  "/confirmation": ["/en/", 301],
  "/contact": ["/en/contact/", 301],
  "/datenschutzerklarung": ["/datenschutz/", 301],
  "/de-team/bogdan-cristea": ["/winterthur/team/", 301],
  "/de-team/joao-wt": ["/winterthur/team/", 301],
  "/de-team/laszlo-simo-wt": ["/winterthur/team/", 301],
  "/de-team/ruben-crawford-wt": ["/winterthur/team/", 301],
  "/de-team/sam-wt": ["/winterthur/team/", 301],
  "/de-team/sergei-wt": ["/winterthur/team/", 301],
  "/de/agb": ["/agb/", 301],
  "/de/kids-training-winterthur": ["/winterthur/kurse/little-ninjas/", 301],
  "/de/kids-training-zurich": ["/zurich/kurse/little-ninjas/", 301],
  "/de/seminars": ["/", 301],
  "/de/winterthur": ["/winterthur/", 301],
  "/de/winterthur/coaches": ["/winterthur/team/", 301],
  "/de/winterthur/kids-training": ["/winterthur/kurse/little-ninjas/", 301],
  "/de/winterthur/kurse": ["/winterthur/kurse/", 301],
  "/de/winterthur/stundenplan": ["/winterthur/stundenplan/", 301],
  "/de/zurich": ["/zurich/", 301],
  "/de/zurich/coaches": ["/zurich/team/", 301],
  "/de/zurich/kids-training": ["/zurich/kurse/little-ninjas/", 301],
  "/de/zurich/kurse": ["/zurich/kurse/", 301],
  "/de/zurich/stundenplan": ["/zurich/stundenplan/", 301],
  "/en-team/bogdan-cristea": ["/en/winterthur/team/", 301],
  "/en-team/joao-wt": ["/en/winterthur/team/", 301],
  "/en-team/ruben-crawford-wt": ["/en/winterthur/team/", 301],
  "/en-team/sam-wt": ["/en/winterthur/team/", 301],
  "/en/kids-training-winterthur": ["/en/winterthur/classes/little-ninjas/", 301],
  "/en/kids-training-zurich": ["/en/zurich/classes/little-ninjas/", 301],
  "/en/littleninjas": ["/en/zurich/classes/little-ninjas/", 301],
  "/en/seminars": ["/en/events/", 301],
  "/en/terms-and-conditions": ["/en/terms/", 301],
  "/en/winterthur/classes/self-defense-for-women": ["/en/winterthur/classes/street-defense/", 301],
  "/en/winterthur/coaches": ["/en/winterthur/team/", 301],
  "/en/winterthur/kids-training": ["/en/winterthur/classes/little-ninjas/", 301],
  "/en/winterthur/timetable": ["/en/winterthur/schedule/", 301],
  "/en/zh/littleninjas-6-9": ["/en/zurich/classes/little-ninjas/", 301],
  "/en/zurich/classes/self-defense-for-women": ["/en/zurich/classes/street-defense/", 301],
  "/en/zurich/coaches": ["/en/zurich/team/", 301],
  "/en/zurich/kids-training": ["/en/zurich/classes/little-ninjas/", 301],
  "/en/zurich/timetable": ["/en/zurich/schedule/", 301],
  "/events-2": ["/events/", 301],
  "/feedback-survey": ["/en/cancellation/", 301],
  "/gear": ["/", 302],
  "/gr/bestatigung": ["/", 301],
  "/gr/cancellation": ["/kuendigung/", 301],
  "/gr/danke": ["/", 301],
  "/gr/danke-wt": ["/", 301],
  "/gr/faq": ["/faq/", 301],
  "/gr/feedback-survey": ["/kuendigung/", 301],
  "/gr/gr---blog": ["/articles/", 301],
  "/gr/kontakt": ["/kontakt/", 301],
  "/gr/kurse": ["/zurich/kurse/", 301],
  "/gr/probetraining": ["/probetraining/", 301],
  "/gr/seminare": ["/events/", 301],
  "/gr/stundenplan": ["/zurich/stundenplan/", 301],
  "/gr/stundenplan-winterthur": ["/winterthur/stundenplan/", 301],
  "/gr/trainer": ["/zurich/team/", 301],
  "/gr/uber-uns": ["/ueber-uns/", 301],
  "/gr/winterthur-kurse": ["/winterthur/kurse/", 301],
  "/gr/wt-coaches": ["/winterthur/team/", 301],
  "/gr/zh-coaches": ["/zurich/team/", 301],
  "/gtc-kidstraining": ["/agb-kindertraining/", 301],
  "/home": ["/", 301],
  "/karriere/martial-arts-trainer": ["/karriere/", 301],
  "/karriere/verkaufsprofi1": ["/karriere/", 301],
  "/kurse/fitness-boxen-kickboxen": ["/zurich/kurse/fitness-kickboxen/", 301],
  "/kurse/kickboxen": ["/zurich/kurse/fitness-kickboxen/", 301],
  "/kurse/mma-street-defense": ["/zurich/kurse/street-defense/", 301],
  "/kurse/ringen": ["/zurich/kurse/ringen/", 301],
  "/kurse/selbstverteidigung": ["/zurich/kurse/street-defense/", 301],
  "/kurse/selbstverteidigung-fur-frauen": ["/zurich/kurse/street-defense/", 301],
  "/kurse/street-defense": ["/zurich/kurse/street-defense/", 301],
  "/kurse/thai-boxen-muay-thai": ["/zurich/kurse/muay-thai/", 301],
  "/kurse/winterthur-bjj": ["/winterthur/kurse/bjj/", 301],
  "/kurse/winterthur-boxen": ["/winterthur/kurse/boxen/", 301],
  "/kurse/winterthur-fitness-kickboxen": ["/winterthur/kurse/fitness-kickboxen/", 301],
  "/kurse/winterthur-kickboxen": ["/winterthur/kurse/fitness-kickboxen/", 301],
  "/kurse/winterthur-little-ninjas": ["/winterthur/kurse/little-ninjas/", 301],
  "/kurse/winterthur-mma": ["/winterthur/kurse/mma/", 301],
  "/kurse/winterthur-mma-street-defense": ["/winterthur/kurse/street-defense/", 301],
  "/kurse/winterthur-personal-training": ["/winterthur/kurse/personal-training/", 301],
  "/kurse/winterthur-ringen": ["/winterthur/kurse/ringen/", 301],
  "/kurse/winterthur-selbstverteidigung-fur-frauen": ["/winterthur/kurse/street-defense/", 301],
  "/kurse/winterthur-street-defense": ["/winterthur/kurse/street-defense/", 301],
  "/kurse/winterthur-thai-boxen-muay-thai": ["/winterthur/kurse/muay-thai/", 301],
  "/littleninjas": ["/zurich/kurse/little-ninjas/", 301],
  "/littleninjas/10-14-de-winterthur": ["/winterthur/kurse/little-ninjas/", 301],
  "/littleninjas/10-14-de-zurich": ["/zurich/kurse/little-ninjas/", 301],
  "/littleninjas/10-14-en-winterthur": ["/en/winterthur/classes/little-ninjas/", 301],
  "/littleninjas/10-14-en-zurich": ["/en/zurich/classes/little-ninjas/", 301],
  "/littleninjas/6-9-de-winterthur": ["/winterthur/kurse/little-ninjas/", 301],
  "/littleninjas/6-9-de-zurich": ["/zurich/kurse/little-ninjas/", 301],
  "/littleninjas/6-9-en-winterthur": ["/en/winterthur/classes/little-ninjas/", 301],
  "/littleninjas/6-9-en-zurich": ["/en/zurich/classes/little-ninjas/", 301],
  "/log-in": ["/", 302],
  "/login": ["/", 302],
  "/order-confirmation": ["/", 301],
  "/paypal-checkout": ["/", 301],
  "/privacy-policy": ["/datenschutz/", 301],
  "/reset-password": ["/", 302],
  "/seminare": ["/events/", 301],
  "/seminars": ["/en/events/", 301],
  "/seminars-4": ["/en/events/", 301],
  "/shop": ["/", 302],
  "/sign-up": ["/", 302],
  "/terms-and-conditions": ["/agb/", 301],
  "/test": ["/", 301],
  "/thank-you": ["/en/", 301],
  "/thank-you-wt": ["/en/", 301],
  "/timetable": ["/en/zurich/schedule/", 301],
  "/timetable-witherthur": ["/en/winterthur/schedule/", 301],
  "/trainer/joao-wt": ["/winterthur/team/", 301],
  "/trainer/laszlo-simo-wt": ["/winterthur/team/", 301],
  "/trainer/ruben-crawford-wt": ["/winterthur/team/", 301],
  "/trainer/sam-wt": ["/winterthur/team/", 301],
  "/trainer/samuel-s-bauer-wt": ["/winterthur/team/", 301],
  "/trainer/sergei-wt": ["/winterthur/team/", 301],
  "/trial-session": ["/en/trial/", 301],
  "/trial-session-winterthur": ["/en/trial/", 301],
  "/update-password": ["/", 301],
  "/user-account": ["/", 302],
  "/verification-required": ["/", 301],
  "/winterthur-classes": ["/en/winterthur/classes/", 301],
  "/winterthur-de": ["/winterthur/", 301],
  "/winterthur/kurse/selbstverteidigung-fuer-frauen": ["/winterthur/kurse/street-defense/", 301],
  "/wt-coaches": ["/en/winterthur/team/", 301],
  "/zh-coaches": ["/en/zurich/team/", 301],
  "/zurich-classes": ["/en/zurich/classes/", 301],
  "/zurich-de": ["/zurich/", 301],
  "/zurich/kurse/selbstverteidigung-fuer-frauen": ["/zurich/kurse/street-defense/", 301],
};
const PREFIX = [
  ["/en/littleninjas/", "/en/zurich/classes/little-ninjas/", 301],
  ["/instagram-v2-0/", "/", 301],
  ["/blog-category/", "/articles/", 301],
  ["/littleninjas/", "/zurich/kurse/little-ninjas/", 301],
  ["/en-seminars/", "/en/events/", 301],
  ["/de-seminars/", "/events/", 301],
  ["/seminars/", "/en/events/", 301],
  ["/seminare/", "/events/", 301],
  ["/trainer/", "/zurich/team/", 301],
  ["/product/", "/", 302],
  ["/de-team/", "/zurich/team/", 301],
  ["/en-team/", "/en/zurich/team/", 301],
  ["/career/", "/karriere/", 301],
  ["/en/zh/", "/en/zurich/", 301],
  ["/class/", "/en/zurich/classes/", 301],
  ["/coach/", "/en/zurich/team/", 301],
  ["/tools/", "/", 302],
  ["/blog/", "/articles/", 301],
  ["/shop/", "/", 302],
  ["/gear/", "/", 302],
  ["/gr/", "/", 301],
  ["/de/", "/", 301],
];
// /kurse/<slug> -> /zurich/kurse/<slug>/ wenn die Seite existiert, sonst Kursuebersicht; gleiches Muster fuer /career und /blog
const SLUG = [
  ["/kurse/", "/zurich/kurse/", "/zurich/kurse/"],
  ["/career/", "/karriere/", "/karriere/"],
  ["/blog/", "/articles/", "/articles/"],
];
function go(url, target, code) {
  return Response.redirect(url.origin + target + (url.search || ""), code || 301);
}
export async function onRequest(context) {
  const { request, env, next } = context;
  const url = new URL(request.url);
  let p = url.pathname;
  if (p.startsWith("/api/") || p.startsWith("/assets/")) return next();
  const key = (p.length > 1 && p.endsWith("/")) ? p.slice(0, -1) : p;
  const hit = EXACT[key] || EXACT[key.toLowerCase()];
  if (hit && hit[0] !== p) return go(url, hit[0], hit[1]); // nie auf sich selbst (Schleife)
  for (const [src, base, fallback] of SLUG) {
    if (key.startsWith(src) && key.length > src.length) {
      const slug = key.slice(src.length).split("/")[0].toLowerCase();
      const cand = base + slug + "/";
      if (cand !== p) {
        try { const r = await env.ASSETS.fetch(new Request(url.origin + cand, { method: "HEAD" })); if (r.status === 200) return go(url, cand, 301); } catch {}
        return go(url, fallback, 301);
      }
    }
  }
  for (const [pre, dst, code] of PREFIX) {
    if (key === pre.slice(0, -1) || key.startsWith(pre)) return go(url, dst, code);
  }
  return next();
}
